# 録音対象番組の設定ファイル
programs:
  - station_id: TBS
    station_name: TBSラジオ
    program_name: test_program
    day_of_week: Saturday
    start_time: "10:00"
    duration_minutes: 1
    enabled: true

  - station_id: LFR
    station_name: ニッポン放送
    program_name: sample_program
    day_of_week: Sunday
    start_time: "13:00"
    duration_minutes: 1
    enabled: false

  - station_id: LFR
    station_name: ニッポン放送
    program_name: LFR_test_program_1
    day_of_week: Saturday
    start_time: "05:00"
    duration_minutes: 1
    enabled: true

  - station_id: LFR
    station_name: ニッポン放送
    program_name: LFR_test_program_2
    day_of_week: Saturday
    start_time: "05:01"
    duration_minutes: 1
    enabled: true
