rules:
- name: オードリー
  keyword: オードリー
  enabled: true
- name: 佐久間
  keyword: 佐久間
  enabled: true
- name: さまぁ～ず
  keyword: さまぁ～ず
  enabled: true
- name: ふかわ
  keyword: ふかわ
  enabled: true
- name: 有吉
  keyword: 有吉
  enabled: true
- name: かんきも
  keyword: かんきも
  enabled: true
- name: 伊集院
  keyword: 伊集院
  enabled: true
- name: Creepy
  keyword: Creepy
  enabled: true
- name: 辛坊
  keyword: 辛坊
  enabled: true
- name: 大竹まこと
  keyword: 大竹まこと
  enabled: true
- name: ひろゆき
  keyword: ひろゆき
  enabled: true
- name: 日経電子版NEWS
  keyword: 日経電子版NEWS
  enabled: true
- name: KOO
  keyword: KOO
  enabled: true
